<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="dv-campus-customer-preferences" style="display: none;">
    <h3><?= $block->escapeHtml(__('My Preferences')) ?></h3>
    <ul id="dv-campus-customer-preferences-list"></ul>
    <button type="button"
            class="button"
            id="dv-campus-customer-preferences-edit-button"
            data-mage-init='{"dvCampus_customerPreferences_button": {}}'
    ><?= $block->escapeHtml(__('Edit Preferences')) ?></button>
</div>