<?php /** @var \DvCampus\CustomerPreferences\Block\Form $block */ ?>
<div data-bind="scope: 'customerPreferencesForm'" style="width: 50%; margin: 0 auto;">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customerPreferencesForm": {
                        "component": "dvCampus_customerPreferences_form",
                        "attributes": <?= $block->getAttributesJson() ?>,
                        "action": "<?= $block->escapeUrl($block->getUrl('dv_campus_customer_preferences/preferences/save')) ?>"
                    }
                }
            }
        }
    }
</script>