<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="dv-campus-customer-preferences-sidebar-container" data-bind="scope: 'customerPreferencesSidebar'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#dv-campus-customer-preferences-sidebar-container": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>